version: "3.2"
services:
    web:
        build:
          context: ./
          dockerfile: ./ftsWebApi/Dockerfile
        environment:
            DatabaseConnectionString: "Server=db;Database=testdb;User=sa;Password=Your_password123;"
            LuceneConfiguration__TempDirectory: "/temploc"
        ports:
            - "8000:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
        expose: 
            - "1433"
        ports:
            - "1433:1433"