CREATE TABLE [dbo].[Test_Data]
(
	[Id] INT IDENTITY(1, 1) NOT NULL, 
	[Name] NVARCHAR(256) NOT NULL,
	[Content] NVARCHAR(MAX) NOT NULL,
	[AddedAt] DATETIMEOFFSET NOT NULL,
	[UpdatedAt] DATETIMEOFFSET NULL,
	[DeletedAt] DATETIMEOFFSET NULL,
	CONSTRAINT [PK_Test_Data] PRIMARY KEY ([Id])
)
GO


